### ISSUE TITLE
librarian-chef-audit

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian-chef#1]
Thinking about working on something like [`bundler-audit`](https://github.com/postmodern/bundler-audit). Just wanted to double-check that someone's not already working on this that you're aware of.

The MVP would probably just help a user view the diffs/changelogs of cookbooks that have been updated but not yet committed, so it would be tied to an assumption of git. It would also likely start off with the assumption that versions are tagged and possibly on github, and might just spit out some `compare` urls, like this:
https://github.com/opscode-cookbooks/apt/compare/1.4.8...1.9.0

Thoughts?

**Comment by yfeldblum** [comment]
I'm not aware of anyone working on this.

**Comment by patcon** [comment]
Awesome. Thanks man. Will re-open when I have something to show.
