### ISSUE TITLE
Can't use librarian-chef with latest rails.

### ISSUE THREAD

**Issue by wkf** [applicationsonline/librarian-chef#11]
Rails seems to want json 1.8.0, which makes librarian-chef sad.

```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    librarian-chef (>= 0) ruby depends on
      json (<= 1.5.2, >= 1.4.4) ruby    
    rails (= 3.2.13) ruby depends on
      json (1.8.0)
```

**Comment by yfeldblum** [comment]
I'm not sure how to solve this for you, but `librarian` and `librarian-chef` have very loose dependencies already. `librarian` depends on `json`, but does not constrain that dependency at all. `librarian-chef` depends on `chef >= 0.10`, and `chef` enforces some constrained dependency on `json`.
