### ISSUE TITLE
Tar Support

### ISSUE THREAD

**Issue by thematthopkins** [applicationsonline/librarian-chef#13]
Some cookbooks such as:
cookbook 'apache2-windows'

Have their cookbook stored as a tar:
http://community.opscode.com/api/v1/cookbooks/apache2-windows/versions/0_1_11

Librarian-chef is currently assuming gzipped tars, and throws the exceiption:
/Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:261:in `initialize': not in gzip format (Zlib::GzipFile::Error)
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:261:in`open'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:261:in `unpack_package!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:224:in`cache_version_uri_unpacked!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:340:in`memo'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:88:in`version_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:421:in`fetch_dependencies'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/manifest.rb:121:in `fetch_dependencies!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/manifest.rb:113:in`fetched_dependencies'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/manifest.rb:77:in `dependencies'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:131:in`sourced_dependencies_for_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:60:in `block in recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in`block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in`block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in`each'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in`block in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in`block in scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in`scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in`resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in`block in recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in`block in scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in`scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in`block in map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `each'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in`map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in`block (2 levels) in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in`block in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in`scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in`recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in `block in recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in`block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in`block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in`each'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in`block in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in`block in scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in`scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in`resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in`block in recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in `block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in`block in scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in`scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in `block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in`block in map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `each'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in`map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in `block in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in`block (2 levels) in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in `block in scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in `scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in`block in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in`scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in `resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in`recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:62:in `block in recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:143:in`block (3 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:176:in `block in scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:175:in `scope_checking_manifest'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:142:in`block (2 levels) in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:196:in `block in map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in`each'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:195:in `map_find'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:141:in`block in resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:154:in `block (2 levels) in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:168:in`block in scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in `scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:167:in`scope_checking_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:153:in `block in scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:208:in`scope'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:152:in `scope_resolving_dependency'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:140:in`resolving_dependency_map_find_manifests'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:56:in `recursive_resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver/implementation.rb:32:in`resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/resolver.rb:16:in `resolve'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/action/resolve.rb:26:in`run'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:169:in `resolve!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/cli.rb:41:in`install'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:31:in`returning_status'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `block in bin!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:47:in`with_environment'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-0.1.0/lib/librarian/cli.rb:26:in `bin!'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/librarian-chef-0.0.1/bin/librarian-chef:7:in`<top (required)>'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/bin/librarian-chef:23:in `load'
    from /Users/mhopkins/.rbenv/versions/1.9.3-p429/bin/librarian-chef:23:in`<main>'

**Comment by aaronjensen** [comment]
we're hitting this now too, it's pretty broken and the error message isn't helpful.

**Comment by cromulus** [comment]
same problem here.

**Comment by khouse** [comment]
+1

**Comment by afronski** [comment]
+1, same problem here with npm cookbook (0.1.2).

**Comment by cromulus** [comment]
Could you please push a new version of librarian-chef with these changes up to rubygems.org? There are other gems  (https://github.com/jimmycuadra/vagrant-librarian-chef) that depend on this one that are using the old and busted code, instead of this new hotness.

Thanks!

**Comment by yfeldblum** [comment]
[librarian-chef v0.0.2](https://github.com/applicationsonline/librarian-chef/tree/v0.0.2) released to [rubygems.org](https://rubygems.org/gems/librarian-chef/versions/0.0.2).

**Comment by cromulus** [comment]
Thanks!

sent on the run
