### ISSUE TITLE
Installing gem on Windows fails

### ISSUE THREAD

**Issue by smalldave** [applicationsonline/librarian-chef#19]
Ruby 1.9.3, Gems 1.8.24.

Chef requires windows-pr (=1.2.1) and mixlib-shellout requires windows-pr (~>1.2.2)

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: chef requires windows-pr (= 1.2.1), win32-process (= 0.6.5); win32-service requires windows-pr (>= 1.0.8); win32-dir requires windows-pr (>= 1.0.9); mixlib-shellout requires win32-process (~> 0.7.0), windows-pr (~> 1.2.2)

**Comment by yfeldblum** [comment]
Unfortunately I can't fix it from Librarian-Chef`'s gemspec. I'm not sure where these dependencies are and was not able to reproduce on my non-Windows machine, but that would be a conflict in Chef's dependencies and Librarian-Chef does depend on Chef.

You can possibly use Bundler to resolve the dependencies automatically or with hints, or you can resolve the dependencies yourself by discovering and installing a consistent set of gems.

**Comment by neilhoff** [comment]
I am getting this same error.  Did you find a fix?

**Comment by neilhoff** [comment]
I was able to get around it by using Bundler like you said.  Here is the GEMFILE that got me around the error:

```
source 'https://rubygems.org'

gem 'windows-pr', '1.2.1'
gem 'win32-process', '0.6.5'
```
