### ISSUE TITLE
Feature request - Configure Cheffile path

### ISSUE THREAD

**Issue by borntyping** [applicationsonline/librarian-chef#20]
When using the [knife integration](https://github.com/applicationsonline/librarian-chef#knife-integration), all knife commands fail when used outside the chef repository, as librarian-chef cannot find the Cheffile. Would it be possible allow the path to the Cheffile to be configured in `~/.chef/knife.rb`, so that the integration can be used when outside the repository?

**Comment by eheydrick** [comment]
+1. You shouldn't have to be in the repo to run knife commands.
