### ISSUE TITLE
http_proxy environment not captured... Is this a possible solution?

### ISSUE THREAD

**Issue by marcellodesales** [applicationsonline/librarian-chef#27]
Hi all,
I installed librarian-chef through "gem" after a battle on my server for using an http_proxy... While trying to use librarian-chef, I got timeout errors which indicate it is my http_proxy variables set... 

[root@pppdc9prd0h2 cfp-dev]# librarian-chef update
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

I can perfectly "git clone", download "gems", etc using the proxy configured:

[root@pppdc9prd0h2 cfp-dev]# cat /app/proxy.sh
export http_proxy=http://qypprdproxy02.iex.net:80
export https_proxy=http://qypprdproxy02.iex.net:80
export ftp_proxy=http://qypprdproxy02.iex.net:80
export HTTP_PROXY=http://qypprdproxy02.iex.net:80
export FTP_PROXY=http://qypprdproxy02.iex.net:80
[root@pppdc9prd0h2 cfp-dev]# . /app/proxy.sh
[root@pppdc9prd0h2 cfp-dev]# echo $http_proxy
http://qypprdproxy02.ie.intuit.net:80

So I found out that librarian-puppet supports http_proxy and the hack is located here:

https://github.com/rodjek/librarian-puppet/issues/76

How can I test a similar patch for librarian-chef? I changed on my local environment the following source:

/usr/local/rvm/gems/ruby-2.1.0-bundler/gems/librarian-chef-0.0.2/lib/librarian/chef/source/site.rb"

```
          proxy = Net::HTTP::Proxy('qypprdproxy02.ie.intuit.net', 80)
          response = proxy.get_response(URI.parse("#{uri.path}"))
          #request = Net::HTTP::Get.new(uri.path)
          #response = http.start{|http| http.request(request)}
```

How can I verify this patch? I can't find the source version installed here in your repo...

https://github.com/marcellodesales/librarian-chef/blob/master/spec/integration/chef/source/site_spec.rb

**Comment by yfeldblum** [comment]
I'm not able to replicate.

I tested this running `librarian-chef update` with `http_proxy` set to [a local http proxy](https://banu.com/tinyproxy/). I can see from my proxy's log that the HTTP requests are going through the proxy.
