### ISSUE TITLE
gem install failing with Xcode/clang 5.1

### ISSUE THREAD

**Issue by jlorich** [applicationsonline/librarian-chef#31]
Since upgrading to Xcode/clang 5.1 the installation of yajl-ruby and puma fail ([yajl-ruby issue](https://github.com/brianmario/yajl-ruby/issues/134), [puma issue](https://github.com/puma/puma/issues/499).  It looks like clang 5.1 now fails on unknown command line arguments.  Though this is not a problem directly with librarian-chef I feel an issue here is warranted to help others since I managed to get it working.

Heres a error portion of the log:

```
2 warnings generated.
compiling yajl_lex.c
compiling yajl_parser.c
compiling yajl_version.c
linking shared-object yajl/yajl.bundle
clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: *** [yajl.bundle] Error 1
```

I was able to get around this by setting the ARCHFLAGS environment variable before installing (see example below).  This is not ideal, but works until the dependent gems are updated.

To successfully install librarian-chef after upgrading to Xcode 5.1 simply run:

```
sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install librarian-chef
```

**Comment by fields** [comment]
I'm wondering if this is related to this issue - I got the gems installed successfully, but now when I try to install the cookbooks, it takes forever to pull them down. Has anyone else seen this problem?

**Comment by rogeriopradoj** [comment]
Same for me. @jlorich's workaround solved the problem:

> To successfully install librarian-chef after upgrading to Xcode 5.1 simply run:
> 
> ```
> sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install librarian-chef
> ```

**Comment by andygrunwald** [comment]
I got the same error.
Here is a complete shell output: https://gist.github.com/andygrunwald/10544034

The workaround from @rogeriopradoj works. Thanks.
