### ISSUE TITLE
Allow to select branch

### ISSUE THREAD

**Issue by Mic92** [applicationsonline/librarian-chef#4]
Sometimes there is a fix for a cookbook, which is only available in a feature branch.

**Comment by yfeldblum** [comment]
```
cookbook "cb-name",
  :github => "me/my-fork",
  :ref => "my-feature-branch"
```

**Comment by Mic92** [comment]
Ok. I thought, the ref option selects git tags because of the example:

```
cookbook "rvm",
  :git => "https://github.com/fnichol/chef-rvm",
  :ref => "v0.7.1"
```

Is it actually possible to select git tags?

**Comment by yfeldblum** [comment]
Yes, you can use the `:ref =>` option to select any of the following:
- branch
- tag
- annotated tag
- commit sha
