### ISSUE TITLE
librarian-chef install: Doesn't stop running git commands even though initial clone failed.

### ISSUE THREAD

**Issue by kallebertell** [applicationsonline/librarian-chef#6]
Didn't have network when I ran librarian-chef install and git clone for a cookbook hosted on github failed.

However, it continued to run git commands (git reset --hard, git clean ...) in the empty directory which is not a git repository since the clone failed. 

Since I'm running librarian-chef from my own git repository, it started reseting and cleaning this repository (since the git command traverses up the directory structure until it find a git repo).

**Comment by yfeldblum** [comment]
Should be fixed in https://github.com/applicationsonline/librarian/commit/dfc57c20e3a782365a458bff563c1ced85eeaa8e.
